### ISSUE TITLE
Possibility to provide auth-ID pattern as tenant configuration

### ISSUE THREAD

**Issue by alinaserg** [eclipse-hono/hono#2825]
With introduction of auto-registration feature there's possibility to configure device-id pattern, which is used during device registration process, see: [#2664](https://github.com/eclipse/hono/issues/2664).

I think it would be also helpful to provide similar configuration for auth-id which is created during device registration process and used for device authentication. Currently auth-id for certificate based device authentication completely corresponds to subject-DN of device certificate.

I'll try to explain it with the help of one example:

The client certificates of devices in the field can be renewed and updated. The renewed certificates can contain some changes in subject-DN, e.g. the department name is changed. In such case subject-DN of the client certificate will not be similar to the subject-DN from the old certificate. And when such device will try to connect with a new certificate the authentication will fail as auth-id (subject-DN) registered in Device Registry will not match with auth-id (subject-DN) from the new client certificate.

In such case it would be helpful to provide possibility to configure which parts from Subject-DN should be used for auth-id, which are not affected and changed by certificate renewal and stay stable and unique during the whole lifecycle of the device.

See below examples of possible auth-id patterns:

`auth-id-pattern: "{{subject-CN}}"` -> only use the subject CN from the device certificate

`auth-id-pattern: "{{subject-DN}}" `-> use the subject DN from the device certificate

WDYT?

**Comment by b-abel** [comment]
At least in the example, it's more about selecting certain attributes from the subject to be used in the authentication. I wonder if it would be better to specify a list of attributes rather than a pattern. That would be easier to use because not all possible attributes and their order would have to be considered. @alinaserg @sophokles73 WDYT?

**Comment by alinaserg** [comment]
@b-abel, for me your proposal sounds reasonable. I don't see anything that speaks against of this approach.

**Comment by b-abel** [comment]
So, I summarize what we want here:
1. Define a list of placeholders and document them in the Management API. We start with the following:
  - {{subject-CN}}
  - {{subject-DN}}
  - {{subject-OU}}
2. The auth-id pattern is resolved with the values from the device cert during the (auto-)provisioning process.
3. During the authentication of a device, the pattern (the Management API calls it *template*, I think we should keep that) is taken from the tenant stored in the database, the placeholders are replaced with the values from the certificate of the device that tries to authenticate and then checked if the result matches the auth-id from the stored credentials.

Constraints that need to be documented:
- when a new certificate is issued for a device, the values for the used placeholders must not be the same that are used during the provisioning.
- the pattern defined for a tenant registration must not be changed, otherwise, the authentication of existing devices will fail.

**Comment by kaniyan** [comment]
Currently _device-id_ template configuration supports placeholders namely `{{subject-cn}}` and `{{subject-dn}}`. I think it's good to support also another subjectDN's attribute _Organizational Unit Name_ (`{{subject-ou}}`). We can make the _auth-id_ template in sync with that of the _device-id_ template to support `{{subject-cn}}`,  `{{subject-dn}}` and `{{subject-ou}}`.

**Comment by sophokles73** [comment]
When supporting `OU` it also seems very reasonable to support `O` as well, as `OU` is usually used to indicate a sub-unit of a larger organization, e.g. `O=ACME Inc.` and `OU=Marketing Dept`.

**Comment by sophokles73** [comment]
> Constraints that need to be documented:
>* when a new certificate is issued for a device, the values for the used placeholders must not be the same that are used during the provisioning.
>* the pattern defined for a tenant registration must not be changed, otherwise, the authentication of existing devices will fail.

I agree with the latter one. If the template is being changed for an existing trust anchor, then we have no chance of successfully authenticating the devices anymore.

With the former I disagree. FMPOV the opposite is true, i.e. when a new certificate is being issued to *the same* device, then the values for the place holders actually need to be identical to the values that were used when the device was (auto-)registered. Otherwise the auth-id determined for the device when it authenticates would not match the registered auth-id anymore, would it?

@kaniyan Looks like we had already established the fact that the auth-id template must not be changed after registration.

**Comment by b-abel** [comment]
> when a new certificate is being issued to _the same_ device, then the values for the place holders actually need to be identical to the values that were used when the device was (auto-)registered.

Sorry, my bad. That is what I actually wanted to say. I just messed up the sentence to say the exact opposite. I'll fix it.

**Comment by kaniyan** [comment]
> With the former I disagree. FMPOV the opposite is true, i.e. when a new certificate is being issued to _the same_ device, then the values for the place holders actually need to be identical to the values that were used when the device was (auto-)registered. Otherwise the auth-id determined for the device when it authenticates would not match the registered auth-id anymore, would it?

I disagree too for the first point. The values of the placeholders should remain the same.

> @kaniyan Looks like we had already established the fact that the auth-id template must not be changed after registration.

Tried to make it resilent to template modifications. After analysis and considering the changes involved, it seems that we go ahead with the constraint. In future, if it has any practical disadvantages, we can still go back to the analysis that we discussed in  [#2968](https://github.com/eclipse/hono/pull/2968#issuecomment-979146644).

**Comment by n-deliyski** [comment]
This feature looks still relevant.
The device certificates are renewed on certain period and modification on the Subject-DN is possible.

Currently the handing of this use case is to add manually for each device a credential record with the new Subject-DN.

The feature will save operational work mostly when the device is provisioned using the template from the beginning.
If the device was provisioned before the template and the Subject-DN is changed, it still be required manual work to add credential record for each device.

Regarding code modifications, most of the work seems done - some pieces are already merged and there is one pending PR #2985

Do you remember why it was not completed, any obstacles or concerns?
May I join and help to finish it?

**Comment by sophokles73** [comment]
@n-deliyski sorry for the delay. I currently can not spend as much time on Hono as I would like to ;-)
IIRC the reason for not merging #2985 was that @kaniyan and I agreed that it would be better to first refactor the whole mechanism of mapping the value objects to/from JSON because with the current approach, the code would become less and less manageable. If you are still interested to jump in here I could try refresh my memory of my original discussions with @kaniyan and get back to you with an update.
@kaniyan anything to add?

**Comment by n-deliyski** [comment]
@sophokles73, yes, I want to jump here.

It is not clear enough for me why we need https://github.com/eclipse-hono/hono/pull/2985.
The original requirement was to support auth-id based on some fields of the device subject-DN (not the whole DN).
It was not required to support changes of the values of the fields of the device subject-DN or changes on the template itself.
If there is such change then someone has to go manually and add credential record based on the new subject-DN. Is that not enough?

**Comment by n-deliyski** [comment]
As continuation of my previous comment I have tested the auto provisioning via auth-id template using the the current master and a running cluster.
The result was that it did not work. There was exception during auth-id conversion inside DeviceAndGatewayAutoProvisioner class.
I am not sure if this error was left on purpose with https://github.com/eclipse-hono/hono/pull/2958 but it breaks the execution.
The PR https://github.com/eclipse-hono/hono/pull/3475 fixes that by adding support of the generated auth-id in X509CertificateCredential class.
@sophokles73 could you please take a look if the proposed change fits inside the general auth-id template functionality?

**Comment by sophokles73** [comment]
@n-deliyski first of all, I have to apologize for not getting back to you on your previous comment. I am currently finding only very limited time to work on Hono. I will take a look this evening and provide some feedback.
